#!/bin/bash

mkdir data

for field in $(seq 0.0  0.1  2.0)
do 
    mkdir lambda$field
    cp 2d_kitaev_vacancy_flux_extraction.jl lambda$field/2d_kitaev_vacancy_flux_extraction.jl
    
    cd lambda$field
        # Linux version
        sed -i "s/lambda_left=1.0/lambda_left=$field/g" 2d_kitaev_vacancy_flux_extraction.jl
        
        # # # MacOS version
        # sed -i "" "s/h=0.0/h=$field/g" 2d_kitaev_honeycomb.jl
    cd ..  
done

# Generate the input file to use disBatch
python3 Generate_disBatch_Input_File_lambda.py 
    
# Job submission on rusty
sbatch -n 21 -c 8 -t 7-0:0:0 -p ccq --constraint=rome disBatch kitaev

# sbatch -n 250 -c 8 -t 7-0:0:0 -p ccq --constraint=rome disBatch kitaev2

# # # Job submission on popeye
# # sbatch -n 500 -c 4 -t 7-0:0:0 -p ccq --constraint=cascadelake disBatch kitaev