#!/bin/bash

lambda_array=(0.06  0.07  0.08  0.09  0.1)
lambda_left=(0.06  0.06  -0.06  -0.06  0.07  0.07  -0.07  -0.07  0.08  0.08  -0.08  -0.08  0.09  0.09  -0.09  -0.09  0.1  0.1  -0.1  -0.1)
lambda_right=(0.06  -0.06  0.06  -0.06  0.07  -0.07  0.07  -0.07  0.08  -0.08  0.08  -0.08  0.09  -0.09  0.09  -0.09  0.1  -0.1  0.1  -0.1)
configuration=("WL+1_WR+1" "WL+1_WR-1" "WL-1_WR+1" "WL-1_WR-1")

# Create the directories for different lambda values, and perturbation configurations
for index1 in ${!lambda_array[@]}
do
    mkdir lambda${lambda_array[index1]}
    cd lambda${lambda_array[index1]}

    path=$(pwd)
    cd /pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/PBC/epsilon1E-10/W3/AFM/
    mkdir lambda${lambda_array[index1]}
    cd $path
    
    for index2 in ${!configuration[@]}
    do 
        # echo ${configuration[index2]}
        mkdir ${configuration[index2]}
        cd ${configuration[index2]}

        index=$((index1*4+index2))

        cp ../../2d_kitaev_vacancy_reordering_W3.jl 2d_kitaev_vacancy_flux_extraction.jl
        cp ../../CustomObserver.jl  CustomObserver.jl
        cp ../../HoneycombLattice.jl  HoneycombLattice.jl
        cp ../../TopologicalLoops.jl  TopologicalLoops.jl
        cp ../../Entanglement.jl  Entanglement.jl
        cp ../../jobs_submission  jobs_submission

        # Linux version
        sed -i "s/lambda_left=0/lambda_left=${lambda_left[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
        sed -i "s/lambda_right=0/lambda_right=${lambda_right[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
        sed -i "s/lambda_file/lambda${lambda_array[index1]}/g" 2d_kitaev_vacancy_flux_extraction.jl
        sed -i "s/configuration_file/${configuration[index2]}/g" 2d_kitaev_vacancy_flux_extraction.jl  
        sed -i "s/lambda_file/lambda${lambda_array[index1]}/g" jobs_submission
        sed -i "s/configuration_file/${configuration[index2]}/g" jobs_submission
        
        # # MacOS version
        # sed -i " " "s/lambda_left=0/lambda_left=${lambda_left[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
        # sed -i " " "s/lambda_right=0/lambda_right=${lambda_right[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
        # sed -i " " "s/lambda_file/lambda${lambda_array[index1]}/g" 2d_kitaev_vacancy_flux_extraction.jl
        # sed -i " " "s/configuration_file/${configuration[index2]}/g" 2d_kitaev_vacancy_flux_extraction.jl  
        # sed -i " " "s/lambda_file/lambda${lambda_array[index1]}/g" jobs_submission
        # sed -i " " "s/configuration_file/${configuration[index2]}/g" jobs_submission

        mkdir data
        for field in $(seq 0  0.01  0.15)
        do 
            mkdir h$field
            cp 2d_kitaev_vacancy_flux_extraction.jl  h$field/2d_kitaev_vacancy_flux_extraction.jl
            
            cd h$field
                # # Linux version
                sed -i "s/h=0.0/h=$field/g" 2d_kitaev_vacancy_flux_extraction.jl
                
                # # MacOS version
                # sed -i "" "s/h=0.0/h=$field/g" 2d_kitaev_vacancy_flux_extraction.jl
            cd ..  
        done

        tmp_path=$(pwd)
        cd /pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/PBC/epsilon1E-10/W3/AFM/lambda${lambda_array[index1]}
        mkdir ${configuration[index2]}
        cd ${configuration[index2]}
        mkdir data
        cd $tmp_path 

        sbatch jobs_submission
        cd ..
    done

    cd ..
done