#!/bin/bash

fields=(0.0001)
lambda_array=($(seq 0.05  0.01  0.12))
lambda_left=(-0.05  -0.05  -0.06  -0.06  -0.07  -0.07  -0.08  -0.08  -0.09  -0.09  -0.1  -0.1  -0.11  -0.11  -0.12  -0.12)
lambda_right=(0.05  -0.05  0.06  -0.06  0.07  -0.07  0.08  -0.08  0.09  -0.09  0.1  -0.1  0.11  -0.11  0.12  -0.12)
configuration=("WL-1_WR+1"  "WL-1_WR-1")

# Create the directories for different lambda values, and perturbation configurations
for field in "${fields[@]}"
do 
    cp jobs_submission_lambda  h$field/jobs_submission_lambda2
    
    cd h$field
        # # # Linux version
        sed -i "s/nid000000/nid004160/g"  jobs_submission_lambda2 
        
        # # MacOS version
        # sed -i "" "s/h=0.0/h=$field/g" 2d_kitaev_vacancy_flux_extraction.jl

        for index1 in ${!configuration[@]}
        do 
            # echo ${configuration[index1]}
            echo $index1
            mkdir ${configuration[index1]}
            cd ${configuration[index1]}


            # Linux version
            sed -i "s/field_file/h$field/g" ../jobs_submission_lambda2
            if [[ "${configuration[index1]}" == "WL-1_WR+1" ]]; then
                sed -i "s/TMP1/${configuration[index1]}/g" ../jobs_submission_lambda2
            elif [[ "${configuration[index1]}" == "WL-1_WR-1" ]]; then 
                sed -i "s/TMP2/${configuration[index1]}/g" ../jobs_submission_lambda2
            fi

            # ## MacOS version
            # sed -i "" "s/field_file/h$field/g" jobs_submission_lambda
            # sed -i "" "s/configuration_file/${configuration[index1]}/g" jobs_submission_lambda

            path=$(pwd)
            cd /pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/TBC/epsilon1E-10/W4/AFM_Refine/h$field
            mkdir ${configuration[index1]}
            cd ${configuration[index1]}
            mkdir data
            cd $path

            for index2 in ${!lambda_array[@]}
            do
                mkdir lambda${lambda_array[index2]}
                cd lambda${lambda_array[index2]}

                index=$((index2*2+index1))
                cp ../../2d_kitaev_vacancy_flux_extraction.jl 2d_kitaev_vacancy_flux_extraction.jl
                
                # Linux version
                sed -i "s/lambda_left=0/lambda_left=${lambda_left[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
                sed -i "s/lambda_right=0/lambda_right=${lambda_right[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
                sed -i "s/field_file/h$field/g" 2d_kitaev_vacancy_flux_extraction.jl
                sed -i "s/configuration_file/${configuration[index2]}/g" 2d_kitaev_vacancy_flux_extraction.jl  
                
                # # MacOS version
                # sed -i "" "s/lambda_left=0/lambda_left=${lambda_left[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
                # sed -i "" "s/lambda_right=0/lambda_right=${lambda_right[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
                # sed -i "" "s/field_file/h$field/g" 2d_kitaev_vacancy_flux_extraction.jl
                # sed -i "" "s/configuration_file/${configuration[index2]}/g" 2d_kitaev_vacancy_flux_extraction.jl    
                
                cd ..
            done            

            cd ..
        done
    
    sbatch jobs_submission_lambda2
    cd .. 
done