#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=8
#SBATCH --constraint=cpu
#SBATCH --qos=premium
#SBATCH -J t0.05
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -t 48:00:00


# # Set up the Julia environment
# module purge; module load julia/1.10.4


for kappa in $(seq -0.5  0.025  -0.125)
do
    cd kappa$kappa
    srun -n 1 julia --threads=1 2d_tK_honeycomb.jl > t-Kitaev_$kappa.log &
    cd ..    
done


wait