#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=8
#SBATCH --constraint=cpu
#SBATCH --reservation=kitaev
#SBATCH -J kitaev
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -t 150:00:00


# # Set up the Julia environment
# module purge; module load julia/1.10.4


for lambda in $(seq 0.05  0.01  0.12)
do 
    cd /global/homes/x/xiaobo23/tensor_networks/quantum_spin_liquids/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/Armchair/epsilon1E-10/W4/FM_Refine/field_file/TMP1/lambda$lambda
    srun -n 1 julia --threads=1 2d_kitaev_armchair_vacancy.jl > kitaev_honeycomb_vacancy$lambda.log &
done

for lambda in $(seq 0.05  0.01  0.12)
do 
    cd /global/homes/x/xiaobo23/tensor_networks/quantum_spin_liquids/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/Armchair/epsilon1E-10/W4/FM_Refine/field_file/TMP2/lambda$lambda
    srun -n 1 julia --threads=1 2d_kitaev_armchair_vacancy.jl > kitaev_honeycomb_vacancy$lambda.log &
done


wait