#!/bin/bash

fields=(0.007)
lambda_array=($(seq 0.05  0.01  0.12))
lambda_left=(0.05  0.05  0.06  0.06  0.07  0.07  0.08  0.08  0.09  0.09  0.1  0.1  0.11  0.11  0.12  0.12)
lambda_right=(0.05  -0.05  0.06  -0.06  0.07  -0.07  0.08  -0.08  0.09  -0.09  0.1  -0.1  0.11  -0.11  0.12  -0.12)
configuration=("WL+1_WR+1"  "WL+1_WR-1")

# Create the directories for different lambda values, and perturbation configurations
for field in "${fields[@]}"
do 
    mkdir h$field
    cp 2d_kitaev_armchair_vacancy.jl  h$field/2d_kitaev_armchair_vacancy.jl
    cp CustomObserver.jl  h$field/CustomObserver.jl
    cp HoneycombLattice.jl  h$field/HoneycombLattice.jl
    cp TopologicalLoops.jl  h$field/TopologicalLoops.jl
    cp Entanglement.jl  h$field/Entanglement.jl
    cp jobs_submission_lambda  h$field/jobs_submission_lambda1

    
    path=$(pwd)
    cd /pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/Armchair/epsilon1E-10/W4/FM_Refine/
    mkdir h$field
    cd $path
    
    cd h$field
        # # Linux version
        sed -i "s/h=0.0/h=$field/g" 2d_kitaev_armchair_vacancy.jl
        # sed -i "s/nid000000/nid004161/g"  jobs_submission_lambda1
        
        # # MacOS version
        # sed -i "" "s/h=0.0/h=$field/g" 2d_kitaev_vacancy_flux_extraction.jl

        for index1 in ${!configuration[@]}
        do 
            # echo ${configuration[index1]}
            echo $index1
            mkdir ${configuration[index1]}
            cd ${configuration[index1]}
            # cp ../jobs_submission_lambda jobs_submission_lambda

            # Linux version
            sed -i "s/field_file/h$field/g" ../jobs_submission_lambda1
            if [[ "${configuration[index1]}" == "WL+1_WR+1" ]]; then
                sed -i "s/TMP1/${configuration[index1]}/g" ../jobs_submission_lambda1
            elif [[ "${configuration[index1]}" == "WL+1_WR-1" ]]; then 
                sed -i "s/TMP2/${configuration[index1]}/g" ../jobs_submission_lambda1
            fi
        
            # ## MacOS version
            # sed -i "" "s/field_file/h$field/g" jobs_submission_lambda
            # sed -i "" "s/configuration_file/${configuration[index1]}/g" jobs_submission_lambda


            path=$(pwd)
            cd /pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/kitaev/magnetic_fields/vacancy/extraction/Armchair/epsilon1E-10/W4/FM_Refine/h$field
            mkdir ${configuration[index1]}
            cd ${configuration[index1]}
            mkdir data
            cd $path

            for index2 in ${!lambda_array[@]}
            do
                mkdir lambda${lambda_array[index2]}
                cd lambda${lambda_array[index2]}

                index=$((index2*2+index1))
                cp ../../2d_kitaev_armchair_vacancy.jl 2d_kitaev_armchair_vacancy.jl
                

                # Linux version
                sed -i "s/lambda_left=0/lambda_left=${lambda_left[index]}/g" 2d_kitaev_armchair_vacancy.jl
                sed -i "s/lambda_right=0/lambda_right=${lambda_right[index]}/g" 2d_kitaev_armchair_vacancy.jl
                sed -i "s/field_file/h$field/g" 2d_kitaev_armchair_vacancy.jl
                sed -i "s/configuration_file/${configuration[index2]}/g" 2d_kitaev_armchair_vacancy.jl 
                
                # # MacOS version
                # sed -i "" "s/lambda_left=0/lambda_left=${lambda_left[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
                # sed -i "" "s/lambda_right=0/lambda_right=${lambda_right[index]}/g" 2d_kitaev_vacancy_flux_extraction.jl
                # sed -i "" "s/field_file/h$field/g" 2d_kitaev_vacancy_flux_extraction.jl
                # sed -i "" "s/configuration_file/${configuration[index2]}/g" 2d_kitaev_vacancy_flux_extraction.jl    
                
                cd ..
            done            

            # sbatch jobs_submission_lambda
            cd ..
        done
    
    sbatch jobs_submission_lambda1
    cd .. 
done
