#!/bin/bash

for idx in $(seq -0.5  0.025  -0.125)
do
    mkdir kappa$idx
    cp 2d_tK_honeycomb.jl kappa$idx/2d_tK_honeycomb.jl
    
    # Linux version
    sed -i "s/kappa=0/kappa=$idx/g" kappa$idx/2d_tK_honeycomb.jl

    # # MacOS version
    # sed -i "" "s/kappa=0/kappa=$idx/g" kappa$idx/2d_tK_honeycomb.jl

done

if [ ! -d "/pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/t-Kitaev/AFM/W3/Lx12/t0.05_opt1/data/" ]; then
    mkdir /pscratch/sd/x/xiaobo23/TensorNetworks/non_abelian_anyons/t-Kitaev/AFM/W3/Lx12/t0.05_opt1/data/
fi

sbatch jobs_submission